# Generated by Django 2.0 on 2020-07-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_questionnaire',
            name='q8',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
