# Generated by Django 2.0 on 2020-07-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_questionnaire',
            name='q6',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='t_questionnaire',
            name='q7',
            field=models.CharField(max_length=10),
        ),
    ]
