# Generated by Django 2.0 on 2020-07-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200711_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_questionnaire',
            name='q6',
            field=models.CharField(max_length=40),
        ),
    ]
