# Generated by Django 2.0 on 2020-07-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_t_questionnaire_q8'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_questionnaire',
            name='q9',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
