# Generated by Django 2.0 on 2020-07-13 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0009_remove_t_accts_root'),
        ('questions', '0004_auto_20200713_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_questionnaire',
            name='rootid',
            field=models.ForeignKey(default='1000', on_delete=django.db.models.deletion.CASCADE, to='joins.t_accts'),
        ),
    ]
