# Generated by Django 2.0 on 2020-07-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_t_questionnaire_rootid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_questionnaire',
            name='rootid',
            field=models.IntegerField(),
        ),
    ]
