# Generated by Django 2.0 on 2020-07-13 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20200713_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_questionnaire',
            name='rootid',
            field=models.ForeignKey(default='1000', on_delete=django.db.models.deletion.CASCADE, to='joins.t_accts'),
        ),
    ]
