# Generated by Django 2.0 on 2020-07-11 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('joins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_date', models.DateField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('status', models.CharField(default='', max_length=20)),
                ('user', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rootid', models.IntegerField(blank=True, null=True)),
                ('billing_date', models.CharField(default='', max_length=50)),
                ('batch_id', models.CharField(default='', max_length=50)),
                ('user', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_billing_tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('service_date_from', models.DateField(blank=True, null=True)),
                ('service_date_to', models.DateField(blank=True, null=True)),
                ('amount_billed', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
                ('notes', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('payment_status', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('client_number', models.IntegerField(blank=True, null=True)),
                ('user', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rootid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joins.t_accts')),
            ],
        ),
        migrations.CreateModel(
            name='t_care_giver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_attendant', models.IntegerField(blank=True, default=1, null=True)),
                ('user', models.IntegerField(blank=True, default=1, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=20, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=12, null=True)),
                ('lname', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.CharField(blank=True, max_length=15, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ssn', models.CharField(blank=True, max_length=25, null=True)),
                ('client_number', models.IntegerField(blank=True, null=True)),
                ('soc', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.IntegerField(blank=True, default=1, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='t_care_giver',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.t_client'),
        ),
        migrations.AddField(
            model_name='t_batch',
            name='rootid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.t_bill'),
        ),
    ]
