# Generated by Django 2.2.6 on 2019-10-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_client',
            name='dob',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
