# Generated by Django 2.2.6 on 2019-10-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20191014_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_client',
            name='soc',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
