# Generated by Django 2.2.6 on 2019-10-14 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_t_care_giver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='t_care_giver',
        ),
    ]
