# Generated by Django 2.2.6 on 2019-10-14 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_t_care_giver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_care_giver',
            old_name='tracker',
            new_name='client',
        ),
    ]
