# Generated by Django 2.2.6 on 2019-10-25 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0016_auto_20191025_1003'),
        ('client', '0008_t_billing_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_billing_tracker',
            name='root',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='joins.t_accts'),
        ),
        migrations.AlterField(
            model_name='t_billing_tracker',
            name='rootid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
