# Generated by Django 2.2.6 on 2019-10-28 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_remove_t_billing_tracker_root'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_billing_tracker',
            old_name='date',
            new_name='billed_until_date',
        ),
        migrations.AddField(
            model_name='t_billing_tracker',
            name='payment_advice_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_billing_tracker',
            name='present_absent_on_batch',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='t_billing_tracker',
            name='start_billing_from_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
