# Generated by Django 2.2.6 on 2019-10-29 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_t_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_billing',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='t_billing',
            name='updated',
        ),
    ]
