# Generated by Django 2.2.6 on 2019-10-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_auto_20191029_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_bill',
            name='client_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='t_bill',
            name='user',
            field=models.IntegerField(),
        ),
    ]
