# Generated by Django 2.2.6 on 2019-11-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_auto_20191029_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_bill',
            name='batch_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
