# Generated by Django 2.2.6 on 2019-11-01 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_t_bill_batch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=10)),
                ('user', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rootid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.t_bill')),
            ],
        ),
    ]
