# Generated by Django 2.2.6 on 2019-11-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_auto_20191107_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_bill',
            name='billing_date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
