# Generated by Django 2.2.6 on 2019-11-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_auto_20191108_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_batch',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
