# Generated by Django 2.2.6 on 2019-11-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0023_auto_20191111_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_bill',
            name='root',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='t_batch',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
