# Generated by Django 2.2.6 on 2019-11-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0024_auto_20191114_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_billing_tracker',
            old_name='previous_denial_reason',
            new_name='claim_id',
        ),
        migrations.RenameField(
            model_name='t_billing_tracker',
            old_name='present_absent_on_batch',
            new_name='payment_status',
        ),
        migrations.RemoveField(
            model_name='t_bill',
            name='root',
        ),
        migrations.RemoveField(
            model_name='t_billing_tracker',
            name='billed_until_date',
        ),
        migrations.RemoveField(
            model_name='t_billing_tracker',
            name='payment_advice_date',
        ),
        migrations.RemoveField(
            model_name='t_billing_tracker',
            name='start_billing_from_date',
        ),
        migrations.RemoveField(
            model_name='t_billing_tracker',
            name='status',
        ),
        migrations.RemoveField(
            model_name='t_billing_tracker',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='t_billing_tracker',
            name='updated',
        ),
        migrations.AddField(
            model_name='t_bill',
            name='rootid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_billing_tracker',
            name='amount_billed',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_billing_tracker',
            name='amount_paid',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_billing_tracker',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='t_billing_tracker',
            name='service_date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_billing_tracker',
            name='service_date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
