# Generated by Django 2.2.6 on 2019-11-20 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_auto_20191120_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_billing_tracker',
            name='rootid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='joins.t_accts'),
            preserve_default=False,
        ),
    ]
