# Generated by Django 2.2.6 on 2019-11-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0026_auto_20191120_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_billing_tracker',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
