# Generated by Django 2.2.6 on 2020-01-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0027_t_billing_tracker_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_bill',
            name='client_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
