# Generated by Django 2.2.6 on 2020-01-03 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0028_auto_20200103_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_bill',
            name='client_number',
        ),
    ]
