# Generated by Django 2.0 on 2020-07-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_acct',
            name='ser',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
