# Generated by Django 2.2.6 on 2019-10-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_acct',
            name='ssn',
        ),
    ]
