# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-16 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0002_t_acct_ser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_acct',
            name='ser',
        ),
    ]
