# Generated by Django 2.2.6 on 2019-10-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0002_remove_t_acct_ssn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_acct',
            name='doh',
        ),
        migrations.RemoveField(
            model_name='t_acct',
            name='emergency_contact',
        ),
    ]
