# Generated by Django 2.0 on 2020-07-11 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0002_t_accts_rootid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_accts',
            name='rootid',
            field=models.ForeignKey(default='555', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
