# Generated by Django 2.0 on 2020-07-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0003_auto_20200711_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_accts',
            old_name='rootid',
            new_name='root',
        ),
    ]
