# Generated by Django 2.2.6 on 2019-10-11 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0003_auto_20191011_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_acct',
            name='doh',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_acct',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_acct',
            name='ssn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
