# Generated by Django 2.0 on 2020-07-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0005_auto_20200711_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_accts',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
