# Generated by Django 2.2.6 on 2019-10-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0005_t_acct_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_acct',
            name='avatar',
        ),
    ]
