# Generated by Django 2.0 on 2020-07-11 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0006_t_accts_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_accts',
            old_name='rootid',
            new_name='root',
        ),
    ]
