# Generated by Django 2.2.6 on 2019-10-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0007_auto_20191014_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_acct',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='t_acct',
            name='updated',
        ),
    ]
