# Generated by Django 2.0 on 2020-07-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0008_t_accts_rootid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_accts',
            name='root',
        ),
    ]
