# Generated by Django 2.2.6 on 2019-10-14 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0009_auto_20191014_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_acct',
            name='middle_name',
        ),
    ]
