# Generated by Django 2.0 on 2020-07-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0009_remove_t_accts_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_accts',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Attendant', 'Attendant'), ('Client', 'Client'), ('Staff', 'Staff')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='t_accts',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('None-Active', 'None-Active')], max_length=10, null=True),
        ),
    ]
