# Generated by Django 2.0 on 2020-07-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0010_auto_20200714_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_accts',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_accts',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10, null=True),
        ),
    ]
