# Generated by Django 2.2.6 on 2019-10-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0011_t_acct_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_acct_attribute',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='t_acct',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
