# Generated by Django 2.0 on 2020-07-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0012_auto_20200714_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_client_attribute',
            name='rootid',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='t_employee_attribute',
            name='rootid',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='t_evaluation',
            name='rootid',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
