# Generated by Django 2.0 on 2020-07-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0013_auto_20200715_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rootid', models.IntegerField(blank=True, default=1000, null=True)),
                ('fname', models.CharField(blank=True, max_length=20, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('lname', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('account_type', models.CharField(blank=True, choices=[('Attendant', 'Attendant'), ('Client', 'Client'), ('Staff', 'Staff')], max_length=40, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('NoneActive', 'NoneActive')], max_length=20, null=True)),
                ('user', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
