# Generated by Django 2.0 on 2020-07-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200715_1807'),
        ('questions', '0009_auto_20200715_1807'),
        ('joins', '0014_t_accounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='t_accts',
        ),
    ]
