# Generated by Django 2.0 on 2020-07-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0015_delete_t_accts'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_accounts',
            name='ser',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
