# Generated by Django 2.2.6 on 2019-11-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0019_auto_20191106_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_client_attribute',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
