# Generated by Django 2.2.6 on 2019-12-10 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0022_auto_20191210_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_client_attribute',
            name='soc',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
