# Generated by Django 2.2.6 on 2019-12-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0023_auto_20191210_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_accts',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
