# Generated by Django 2.0 on 2020-07-16 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rootid', models.IntegerField(blank=True, default=1000, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('account_type', models.CharField(blank=True, choices=[('Attendant', 'Attendant'), ('Client', 'Client'), ('Staff', 'Staff')], max_length=40, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('NoneActive', 'NoneActive')], max_length=20, null=True)),
                ('user', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_dict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=20)),
                ('status', models.CharField(default='', max_length=20)),
                ('user', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=100)),
                ('document', models.FileField(upload_to='documents/resources/')),
                ('user', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_sub_resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=100)),
                ('document', models.FileField(upload_to='documents/resources/')),
                ('user', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rootid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libs.t_resources')),
            ],
        ),
        migrations.CreateModel(
            name='t_sub_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('url', models.CharField(db_index=True, default='', max_length=100)),
                ('slug', models.SlugField(default='', max_length=100, unique=True)),
                ('toggle', models.CharField(default='modal', max_length=20)),
                ('page_type', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('user', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=20)),
                ('url', models.CharField(default='', max_length=100)),
                ('icon', models.CharField(default='', max_length=20)),
                ('toggle', models.CharField(default='collapse', max_length=20)),
                ('order', models.IntegerField(default='1')),
                ('status', models.CharField(default='', max_length=20)),
                ('user', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='t_sub_url',
            name='rootid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libs.t_url'),
        ),
    ]
