# Generated by Django 2.2.3 on 2019-07-06 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0002_auto_20190706_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='veh_reg',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='libs.Vehicle'),
        ),
    ]
