# Generated by Django 2.0 on 2020-07-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0002_auto_20200713_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_accts',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Attendant', 'Attendant'), ('Client', 'Client'), ('Staff', 'Staff')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='t_accts',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_accts',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='t_accts',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='t_accts',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('None-Active', 'None-Active')], max_length=10, null=True),
        ),
    ]
