# Generated by Django 2.0 on 2020-07-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0003_auto_20200714_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_accts',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('None-Active', 'None-Active')], max_length=20, null=True),
        ),
    ]
