# Generated by Django 2.2.3 on 2019-07-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0006_remove_daily_root_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='driver',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
