# Generated by Django 2.2.6 on 2019-10-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0008_auto_20191011_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_dict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='', max_length=20)),
                ('category', models.CharField(default='', max_length=20)),
                ('status', models.CharField(default='', max_length=20)),
                ('user', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
