# Generated by Django 2.2.6 on 2019-10-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0009_t_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_dict',
            name='header',
            field=models.CharField(default='', max_length=50),
        ),
    ]
