# Generated by Django 2.2.6 on 2019-10-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0012_auto_20191016_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
