# Generated by Django 2.2.6 on 2019-10-21 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0012_auto_20191015_1525'),
        ('libs', '0013_client_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_visit_tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('user', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('employee_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='joins.t_acct')),
            ],
        ),
    ]
