# Generated by Django 2.2.6 on 2019-10-21 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0012_auto_20191015_1525'),
        ('libs', '0014_t_visit_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_visit_tracker',
            name='rootid',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='joins.t_acct'),
        ),
        migrations.AlterField(
            model_name='t_visit_tracker',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
