# Generated by Django 2.2.6 on 2019-10-21 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0015_auto_20191021_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_visit_tracker',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
