# Generated by Django 2.2.6 on 2019-10-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0016_t_visit_tracker_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_visit_tracker',
            name='date',
            field=models.DateField(),
        ),
    ]
