# Generated by Django 2.2.6 on 2019-11-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0017_auto_20191021_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_oig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rootid', models.IntegerField(blank=True, null=True)),
                ('employee_id', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('document', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
