# Generated by Django 2.2.6 on 2019-11-04 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0018_t_oig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_oig',
            name='rootid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joins.t_accts'),
        ),
    ]
