# Generated by Django 2.2.6 on 2019-11-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0019_auto_20191104_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_oig',
            name='employee_id',
        ),
    ]
