# Generated by Django 2.2.6 on 2019-11-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0020_remove_t_oig_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_oig',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
