# Generated by Django 2.2.6 on 2019-11-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0021_auto_20191104_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_oig',
            name='document',
            field=models.FileField(upload_to='documents/oig/'),
        ),
    ]
