# Generated by Django 2.2.6 on 2019-11-08 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0023_t_oig_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_visit_tracker',
            name='rootid',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='joins.t_accts'),
        ),
    ]
