# Generated by Django 2.2.6 on 2019-11-19 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0024_auto_20191108_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=20)),
                ('status', models.CharField(default='', max_length=20)),
                ('user', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_sub_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('user', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rootid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libs.t_url')),
            ],
        ),
    ]
