# Generated by Django 2.2.6 on 2019-11-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0025_t_sub_url_t_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_url',
            name='order',
            field=models.IntegerField(default='1'),
        ),
    ]
