# Generated by Django 2.2.6 on 2019-11-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0026_t_url_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_url',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
