# Generated by Django 2.2.6 on 2019-11-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0027_t_url_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_url',
            name='icon',
            field=models.CharField(default='', max_length=20),
        ),
    ]
