# Generated by Django 2.2.6 on 2019-11-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0029_t_sub_url_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_url',
            name='toggle',
            field=models.CharField(default='collapse', max_length=20),
        ),
    ]
