# Generated by Django 2.2.6 on 2019-11-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0030_t_url_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_sub_url',
            name='toggle',
            field=models.CharField(default='modal', max_length=20),
        ),
    ]
