# Generated by Django 2.2.6 on 2019-11-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0032_t_sub_url_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_sub_url',
            name='page_type',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
