# Generated by Django 2.2.6 on 2019-11-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0033_auto_20191127_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_sub_url',
            name='url',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
