# Generated by Django 2.2.6 on 2019-12-02 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0035_t_sub_url_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_oig',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_oig',
            name='site',
            field=models.CharField(default='', max_length=100),
        ),
    ]
