# Generated by Django 2.2.6 on 2019-12-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0036_auto_20191202_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=100)),
                ('document', models.FileField(upload_to='documents/resources/')),
                ('user', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
