# Generated by Django 2.2.6 on 2019-12-10 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0037_t_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_sub_resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=100)),
                ('document', models.FileField(upload_to='documents/resources/')),
                ('user', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rootid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libs.t_resources')),
            ],
        ),
    ]
