# Generated by Django 2.2.10 on 2020-06-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0039_t_question_t_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_question',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
