# Generated by Django 2.2.10 on 2020-06-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0040_auto_20200626_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_questionnaire',
            name='answer',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
