# Generated by Django 2.2.10 on 2020-06-27 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0042_t_questionnaire_answer1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_questionnaire',
            name='rootid',
        ),
    ]
