# Generated by Django 2.2.10 on 2020-06-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0043_remove_t_questionnaire_rootid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_questionnaire',
            name='answer',
            field=models.BooleanField(choices=[(1, 'yes'), (0, 'No')]),
        ),
    ]
