# Generated by Django 2.2.10 on 2020-06-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0044_auto_20200627_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_questionnaire',
            name='answer',
            field=models.BooleanField(),
        ),
    ]
