# Generated by Django 2.2.10 on 2020-06-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0045_auto_20200627_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_questionnaire',
            name='user',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
