# Generated by Django 2.2.10 on 2020-06-27 21:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0046_auto_20200627_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_questionnaire',
            name='answer1',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Fever of 100 F (37.8 C) or above or possible fever symptoms like alternating chills and sweating', 'Fever of 100 F (37.8 C) or above or possible fever symptoms like alternating chills and sweating'), ('Cough', 'Cough'), ('Trouble breathing or shortness of breath or severe wheezing', 'Trouble breathing, shortness of breath or severe wheezing'), ('Chills or repeated shaking with chills', 'Chills or repeated shaking with chills'), ('Muscle aches', 'Muscle aches'), ('Sore throat', 'Sore throat'), ('Loss of smell or taste, or a change in taste', 'Loss of smell or taste, or a change in taste'), ('Nausea or vomiting or diarrhea', 'Nausea or vomiting or diarrhea'), ('Headache', 'Headache'), ('None of the above', 'None of the above')], max_length=329),
        ),
    ]
