# Generated by Django 2.2.10 on 2020-07-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0048_auto_20200627_2127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='t_question',
        ),
        migrations.DeleteModel(
            name='t_questionnaire',
        ),
    ]
