# Generated by Django 2.2.6 on 2019-11-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippets',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
