# Generated by Django 2.2.10 on 2020-07-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20200706_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_questionnaire',
            name='q6',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
