# Generated by Django 2.2.10 on 2020-07-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_t_questionnaire_q6'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_questionnaire',
            name='q6',
        ),
    ]
