# Generated by Django 2.2.10 on 2020-07-08 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_remove_t_questionnaire_q6'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_questionnaire',
            name='q1',
        ),
    ]
